[[redirects]]
  from = "/purchase/*"
  to = "https://kandksoftware.github.io/macro-terminal-pro/index.html?goto=purchase"
  status = 200
  force = true

[[redirects]]
  from = "/request-demo/*"
  to = "https://kandksoftware.github.io/macro-terminal-pro/demo.html"
  status = 200

[[redirects]]
  from = "/contact/*"
  to = "https://kandksoftware.github.io/macro-terminal-pro/contact.html"
  status = 200  