[[redirects]]
  from = "/css/main.css/*"
  to = "https://kandksoftware.github.io/macro-terminal-pro/css/main.css"
  status = 200
  force = true

[[redirects]]
  from = "/purchase/*"
  to = "https://kandksoftware.github.io/macro-terminal-pro/index.html?goto=purchase"
  status = 200
  force = true

[[redirects]]
  from = "/demo-request/*"
  to = "https://kandksoftware.github.io/macro-terminal-pro/demo.html"
  status = 200

[[redirects]]
  from = "/contact/*"
  to = "https://kandksoftware.github.io/macro-terminal-pro/contact.html"
  status = 200

[[redirects]]
  from = "/js/main.js/*"
  to = "https://kandksoftware.github.io/macro-terminal-pro/js/main.js"
  status = 200
  force = true

[[redirects]]
  from = "/js/script-loader.js/*"
  to = "https://kandksoftware.github.io/macro-terminal-pro/js/script-loader.js"
  status = 200
  force = true
