# netlify.toml - Version: 2024.01.15-01
# Force update by changing this comment date

[build]
  publish = "public"
  command = "echo 'No build command'"

# Catch-all - serve the actual HTML files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200